# Generated by Django 3.1.7 on 2021-03-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youth',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
